language: php

php:
- 5.4
- 5.5
- 5.6

matrix:
  include:
  - php: 5.4
    env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

install:
- echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit
