parameters:
    m6_web_amqp.event.command.class: M6Web\Bundle\AmqpBundle\Event\Command

    m6_web_amqp.producer.class: M6Web\Bundle\AmqpBundle\Producer
    m6_web_amqp.consumer.class: M6Web\Bundle\AmqpBundle\Consumer

    m6_web_amqp.producer_factory.class: M6Web\Bundle\AmqpBundle\Factory\ProducerFactory
    m6_web_amqp.consumer_factory.class: M6Web\Bundle\AmqpBundle\Factory\ConsumerFactory

services:
    m6_web_amqp.producer_factory:
        class: %m6_web_amqp.producer_factory.class%
            
    m6_web_amqp.consumer_factory:
        class: %m6_web_amqp.consumer_factory.class%
